return {
    "images/droppacopter.png",
    "images/hmm.png",
    "images/moaigus.png",
    "images/mowai.png",
    "images/pfp.png",

    "spaceGame/background/background/sol.png",
    "spaceGame/background/background/alpha centauri.png",
    "spaceGame/background/background/proxima centauri.png",
    "spaceGame/background/background/barnardia.png",

    "spaceGame/background/planet/none.png",
    "spaceGame/background/planet/mars.png",
    "spaceGame/background/planet/iris.png",
    "spaceGame/background/planet/copernicus.png",
    "spaceGame/background/planet/vestanew.png",
    "spaceGame/background/planet/novus.png",
    "spaceGame/background/planet/hephaestus.png",
    "spaceGame/background/planet/mercury.png",
    "spaceGame/background/planet/earth.png",
    "spaceGame/background/planet/galilei.png",

    "spaceGame/editor/population/population1.png",
    "spaceGame/editor/population/population2.png",
    "spaceGame/editor/population/population3.png",
    "spaceGame/editor/population/population4.png",

    "spaceGame/editor/tab.png",
    "spaceGame/editor/tabHover.png",
    "spaceGame/editor/tabClicked.png",
    "spaceGame/editor/menu.png",
    "spaceGame/editor/menu2.png",
    "spaceGame/editor/delete.png",

    "spaceGame/editor/objects/station1.png",
    "spaceGame/editor/objects/station2.png",
    "spaceGame/editor/objects/ally1.png",
    "spaceGame/editor/objects/ally2.png",
    "spaceGame/editor/objects/asteroid1.png",
    "spaceGame/editor/objects/asteroid2.png",
    "spaceGame/editor/objects/pirate1.png",
    "spaceGame/editor/objects/pirate1.png", -- Duplicate
    "spaceGame/editor/objects/sign1.png",
    "spaceGame/editor/objects/sign2.png",

    "spaceGame/editor/station/left.png",
    "spaceGame/editor/station/left2.png",
    "spaceGame/editor/station/right.png",
    "spaceGame/editor/station/right2.png",
    "spaceGame/editor/station/delete.png",
    "spaceGame/editor/station/delete2.png",
    "spaceGame/editor/station/close.png",
    "spaceGame/editor/station/close2.png",
    "spaceGame/editor/station/minus.png",
    "spaceGame/editor/station/minus2.png",
    "spaceGame/editor/station/plus.png",
    "spaceGame/editor/station/plus2.png",
    "spaceGame/editor/station/type1.png",
    "spaceGame/editor/station/type12.png",
    "spaceGame/editor/station/type2.png",
    "spaceGame/editor/station/type22.png",
    "spaceGame/editor/station/type3.png",
    "spaceGame/editor/station/type32.png",
    "spaceGame/editor/station/type4.png",
    "spaceGame/editor/station/type42.png",

    "spaceGame/particle/smog.png",
    "spaceGame/particle/gate/spark.png",
    "spaceGame/particle/crate/crate1.png",
    "spaceGame/particle/crate/crate2.png",
    "spaceGame/particle/crate/crate3.png",
    "spaceGame/particle/gate/slab.png",

    "spaceGame/titleScreen/discord/itch.png",
    "spaceGame/titleScreen/discord/itch2.png",
    "spaceGame/titleScreen/titleBanner.png",
    "spaceGame/titleScreen/mouse.png",
    "spaceGame/titleScreen/keyboard.png",

    "spaceGame/jobCenter/buttons/selectButton.png",
    "spaceGame/jobCenter/buttons/selectButton2.png",
    "spaceGame/jobCenter/buttons/selectButton3.png",

    "spaceGame/levelSelect/lore/lore1.png",
    "spaceGame/levelSelect/lore/lore2.png",
    "spaceGame/levelSelect/lore/lore3.png",
    "spaceGame/levelSelect/lore/lore4.png",
    "spaceGame/levelSelect/lore/lore5.png",

    "spaceGame/misc/home1.png",
    "spaceGame/misc/home2.png",
    "spaceGame/misc/back1.png",
    "spaceGame/misc/back2.png",
    "spaceGame/misc/mouse1.png",
    "spaceGame/misc/mouse2.png",

    "spaceGame/loreSlide/",
    "spaceGame/jobCenter/flags/EMP.png",
    "spaceGame/jobCenter/flags/toutorial.png",

    "spaceGame/jobCenter/flags/pirate1.png",
    "spaceGame/jobCenter/flags/pirate4.png",
    "spaceGame/jobCenter/flags/pirate5.png",

    "spaceGame/jobCenter/flags/asteroid1.png",
    "spaceGame/jobCenter/flags/asteroid2.png",
    "spaceGame/jobCenter/flags/asteroid3.png",

    "spaceGame/missionObjects/projectiles/missile.png",
    "spaceGame/missionObjects/projectiles/bullet.png",
    "spaceGame/missionObjects/projectiles/pirateBullet.png",
    "spaceGame/missionObjects/projectiles/ouchMissile.png",

    "spaceGame/missionObjects/ships/player/lilboy.png",
    "spaceGame/missionObjects/ships/player/junge.png",
    "spaceGame/missionObjects/ships/player/eagle.png",
    "spaceGame/missionObjects/ships/player/vulture.png",
    "spaceGame/missionObjects/ships/player/exocoetidae.png",
    "spaceGame/missionObjects/ships/player/xiphiidae.png",
    "spaceGame/missionObjects/ships/player/crayfish.png",
    "spaceGame/missionObjects/ships/player/lobster.png",
    "spaceGame/missionObjects/ships/player/rorqual.png",
    "spaceGame/missionObjects/ships/player/balaenoptera.png",

    "spaceGame/missionObjects/ships/enemy/pirate1.png",
    "spaceGame/missionObjects/ships/enemy/pirate2.png",
    "spaceGame/missionObjects/ships/enemy/pirate3.png",
    "spaceGame/missionObjects/ships/enemy/pirate4.png",
    "spaceGame/missionObjects/ships/enemy/pirate5.png",

    "spaceGame/missionObjects/ships/ally/ally1.png",
    "spaceGame/missionObjects/ships/ally/ally2.png",
    "spaceGame/missionObjects/ships/ally/ally3.png",
    "spaceGame/missionObjects/ships/ally/ally4.png",
    "spaceGame/missionObjects/ships/ally/ally5.png",

    "spaceGame/missionObjects/gate/localGate.png",
    "spaceGame/missionObjects/stations/roundStation01.png",
    "spaceGame/missionObjects/stations/smallStation01.png",

    "spaceGame/missionObjects/stations/flash2.png",
    "spaceGame/missionObjects/stations/flash1.png",

    "spaceGame/missionObjects/asteroids/brown200.png",
    "spaceGame/missionObjects/asteroids/brown400.png",
    "spaceGame/missionObjects/asteroids/brown600.png",

    "spaceGame/jobCenter/buttons/newButton3.png",
    "spaceGame/jobCenter/buttons/newButtonH3.png",
    "spaceGame/jobCenter/buttons/newButtonC3.png",
    "spaceGame/jobCenter/buttons/newButton2.png",
    "spaceGame/jobCenter/buttons/newButtonH2.png",
    "spaceGame/jobCenter/buttons/newButtonC2.png",
    "spaceGame/jobCenter/buttons/newButton1.png",
    "spaceGame/jobCenter/buttons/newButtonH1.png",
    "spaceGame/jobCenter/buttons/newButtonC1.png",
    "spaceGame/jobCenter/buttons/newButton4.png",
    "spaceGame/jobCenter/buttons/newButtonH4.png",
    "spaceGame/jobCenter/buttons/newButtonC4.png",
    "spaceGame/jobCenter/buttons/newButton5.png",
    "spaceGame/jobCenter/buttons/newButtonH5.png",
    "spaceGame/jobCenter/buttons/newButtonC5.png",
    "spaceGame/jobCenter/buttons/newButton6.png",
    "spaceGame/jobCenter/buttons/newButtonH6.png",
    "spaceGame/jobCenter/buttons/newButtonC6.png",
    "spaceGame/jobCenter/buttons/file.png",
    "spaceGame/jobCenter/buttons/delete.png",

    "spaceGame/jobCenter/icons/starEmpty.png",
    "spaceGame/jobCenter/icons/starDiff.png",
    "spaceGame/jobCenter/icons/starFull.png",
    "spaceGame/jobCenter/icons/type1.png",
    "spaceGame/jobCenter/icons/type2.png",
    "spaceGame/jobCenter/icons/type3.png",
    "spaceGame/jobCenter/icons/time.png",
    "spaceGame/jobCenter/icons/box.png",
    "spaceGame/jobCenter/icons/buttonOverlay.png",
    "spaceGame/jobCenter/icons/warning100.png",

    "spaceGame/levelSelect/icons/delivery.png",
    "spaceGame/levelSelect/icons/pickup.png",
    "spaceGame/levelSelect/icons/shop.png",
    "spaceGame/levelSelect/icons/lore.png",
    "spaceGame/levelSelect/icons/locked.png",
    "spaceGame/levelSelect/icons/gate.png",
    "spaceGame/levelSelect/icons/gateLocked.png",
    "spaceGame/levelSelect/star.png",
    "spaceGame/levelSelect/redStar.png",
    "spaceGame/levelSelect/starNot.png",
    "spaceGame/levelSelect/background/sol.png",
    "spaceGame/levelSelect/background/alpha centauri.png",
    "spaceGame/levelSelect/background/proxima centauri.png",
    "spaceGame/levelSelect/background/barnardia.png",
    "spaceGame/levelSelect/planet/vesta.png",
    "spaceGame/levelSelect/planet/mars.png",
    "spaceGame/levelSelect/planet/mercury.png",
    "spaceGame/levelSelect/planet/novus.png",
    "spaceGame/levelSelect/planet/hephaestus.png",
    "spaceGame/levelSelect/planet/copernicus.png",
    "spaceGame/levelSelect/planet/iris.png",
    "spaceGame/levelSelect/planet/earth.png",
    "spaceGame/levelSelect/planet/galilei.png",
    
    -- Ship Menu Icons
    "spaceGame/jobCenter/shipMenu/statIcons/quindocHull.png",
    "spaceGame/jobCenter/shipMenu/statIcons/quindocFuel.png",
    "spaceGame/jobCenter/shipMenu/statIcons/quindocCargo.png",
    "spaceGame/jobCenter/shipMenu/statIcons/quindocAcceleration.png",
    "spaceGame/jobCenter/shipMenu/statIcons/speed.png",
    "spaceGame/jobCenter/shipMenu/statIcons/turn.png",
    "spaceGame/jobCenter/shipMenu/statIcons/dampeners.png",
    "spaceGame/jobCenter/shipMenu/statIcons/quindocCombat.png",
    "spaceGame/jobCenter/shipMenu/statIcons/reload.png",
    "spaceGame/jobCenter/shipMenu/statIcons/dockSpeed.png",
    "spaceGame/jobCenter/shipMenu/statIcons/modules.png",
    "spaceGame/jobCenter/shipMenu/statIcons/weapons.png",
    "spaceGame/jobCenter/shipMenu/statIcons/quindocBoost.png",
    "spaceGame/jobCenter/shipMenu/statIcons/warn.png",
    
    -- Ship Menu Ships
    "spaceGame/jobCenter/shipMenu/ships/lilboy200.png",
    "spaceGame/jobCenter/shipMenu/ships/junge200.png",
    "spaceGame/jobCenter/shipMenu/ships/eagle200.png",
    "spaceGame/jobCenter/shipMenu/ships/vulture200.png",
    "spaceGame/jobCenter/shipMenu/ships/exocoetidae200.png",
    "spaceGame/jobCenter/shipMenu/ships/xiphiidae200.png",
    "spaceGame/jobCenter/shipMenu/ships/crayfish200.png",
    "spaceGame/jobCenter/shipMenu/ships/lobster200.png",
    "spaceGame/jobCenter/shipMenu/ships/rorqual200.png",
    "spaceGame/jobCenter/shipMenu/ships/balaenoptera200.png",
    "spaceGame/jobCenter/shipMenu/ships/lock.png",
    
    -- Modules and Weapons
    "spaceGame/jobCenter/shipMenu/modules/cargo.png",
    "spaceGame/jobCenter/shipMenu/modules/boost.png",
    "spaceGame/jobCenter/shipMenu/modules/regen.png",
    "spaceGame/jobCenter/shipMenu/modules/speed.png",
    "spaceGame/jobCenter/shipMenu/modules/brakes.png",
    "spaceGame/jobCenter/shipMenu/modules/engine.png",
    "spaceGame/jobCenter/shipMenu/modules/dock.png",
    "spaceGame/jobCenter/shipMenu/modules/weapons.png",
    "spaceGame/jobCenter/shipMenu/modules/swam.png",
    "spaceGame/jobCenter/shipMenu/modules/ouch.png",
    "spaceGame/jobCenter/shipMenu/modules/gun.png",
    "spaceGame/jobCenter/shipMenu/modules/flare.png",
    "spaceGame/jobCenter/shipMenu/modules/lock.png",
    
    -- Ticks
    "spaceGame/missionObjects/stations/icons/tick/tick1.png",
    "spaceGame/missionObjects/stations/icons/tick/tick2.png",
    "spaceGame/missionObjects/stations/icons/tick/tick3.png",
    "spaceGame/missionObjects/stations/icons/tick/tick4.png",
    "spaceGame/missionObjects/stations/icons/tick/tick5.png",
    "spaceGame/missionObjects/stations/icons/tick/tick6.png",
    "spaceGame/missionObjects/stations/icons/tick/tick7.png",
    "spaceGame/missionObjects/stations/icons/tick/tick8.png",
    "spaceGame/missionObjects/stations/icons/tick/tick9.png",
    "spaceGame/missionObjects/stations/icons/tick/tick10.png",
    "spaceGame/missionObjects/stations/icons/tick/tick11.png",
    "spaceGame/missionObjects/stations/icons/tick/tick12.png",
    "spaceGame/missionObjects/stations/icons/tick/tick13.png",
    "spaceGame/missionObjects/stations/icons/tick/tick14.png",
    "spaceGame/missionObjects/stations/icons/tick/tick15.png",
    "spaceGame/missionObjects/stations/icons/tick/tick16.png",
    "spaceGame/missionObjects/stations/icons/tick/tick17.png",
    "spaceGame/missionObjects/stations/icons/tick/tick18.png",
    "spaceGame/missionObjects/stations/icons/tick/tick19.png",
    "spaceGame/missionObjects/stations/icons/tick/tick20.png",

    -- Blue Ticks
    "spaceGame/missionObjects/stations/icons/tick/tickBlue1.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue2.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue3.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue4.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue5.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue6.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue7.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue8.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue9.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue10.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue11.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue12.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue13.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue14.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue15.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue16.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue17.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue18.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue19.png",
    "spaceGame/missionObjects/stations/icons/tick/tickBlue20.png",

    -- Yellow Ticks
    "spaceGame/missionObjects/stations/icons/tick/tickYellow1.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow2.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow3.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow4.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow5.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow6.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow7.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow8.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow9.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow10.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow11.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow12.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow13.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow14.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow15.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow16.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow17.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow18.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow19.png",
    "spaceGame/missionObjects/stations/icons/tick/tickYellow20.png",

    -- Cross
    "spaceGame/missionObjects/stations/icons/tick/x.png",

    -- Station Labels
    "spaceGame/minimap/actuallyYOU.png",
    "spaceGame/minimap/pickupLabel.png",
    "spaceGame/minimap/pickupLabelWhite.png",
    "spaceGame/minimap/deliveryLabel.png",
    "spaceGame/minimap/deliveryLabelWhite.png",
    "spaceGame/minimap/fuelLabel.png",
    "spaceGame/minimap/fuelLabelWhite.png",
    "spaceGame/minimap/repairLabel.png",
    "spaceGame/minimap/repairLabelWhite.png",
    "spaceGame/minimap/done.png",
    "spaceGame/minimap/doneWhite.png",
    "spaceGame/minimap/pirate.png",
    "spaceGame/minimap/gate.png",

    -- Gameplay UI Icons
    "spaceGame/missionObjects/stations/icons/exclaim.png",
    "spaceGame/missionObjects/stations/icons/exclaimPickup.png",
    "spaceGame/missionObjects/stations/icons/fuel.png",
    "spaceGame/missionObjects/stations/icons/repair.png",
    -- HUD
    "spaceGame/playerHUD/shipStatus/status.png",
    "spaceGame/playerHUD/shipStatus/statusBackground.png",
    "spaceGame/playerHUD/shipStatus/hullBar.png",
    "spaceGame/playerHUD/shipStatus/cargoBar.png",
    "spaceGame/playerHUD/shipStatus/fuelBar.png",
    "spaceGame/playerHUD/shipStatus/smallCargo.png",

    "spaceGame/playerHUD/weapons/weapons1.png",
    "spaceGame/playerHUD/weapons/weapons2.png",
    "spaceGame/playerHUD/weapons/weapons3.png",

    "spaceGame/playerHUD/weapons/weaponsBackground1.png",
    "spaceGame/playerHUD/weapons/weaponsBackground2.png",
    "spaceGame/playerHUD/weapons/weaponsBackground3.png",

    "spaceGame/playerHUD/sectorList/sectorList.png",
    "spaceGame/playerHUD/sectorList/sectorListBar.png",
    "spaceGame/playerHUD/sectorList/sectorListSector.png",
    "spaceGame/playerHUD/sectorList/sectorListPlayer.png",
    "spaceGame/playerHUD/sectorList/sectorListEnd.png",
    "spaceGame/playerHUD/sectorList/sectorListConnect.png",
    "spaceGame/playerHUD/sectorList/sectorListExtender.png",

    -- Arrows and Status Icons
    "spaceGame/playerHUD/arrow.png",
    "spaceGame/playerHUD/overworldArrow.png",
    "spaceGame/playerHUD/enemyArrow.png",
    "spaceGame/playerHUD/leavingSector.png",

    "spaceGame/playerHUD/threat.png",
    "spaceGame/playerHUD/hostile.png",
    "spaceGame/playerHUD/chase.png",
    "spaceGame/playerHUD/neutral.png",

    "spaceGame/playerHUD/eyeSheet.png",

    -- Targeting spaceGame
    "spaceGame/playerHUD/targeting/ouch.png",
    "spaceGame/playerHUD/targeting/target2.png",
    "spaceGame/playerHUD/targeting/target1.png",
    "spaceGame/playerHUD/targeting/target3.png",
    "spaceGame/playerHUD/targeting/target4.png",

    -- Weapons spaceGame
    "spaceGame/playerHUD/weapons/swarmsol.png",
    "spaceGame/playerHUD/weapons/ouchsmol.png",
    "spaceGame/playerHUD/weapons/gunsmol.png",
    "spaceGame/playerHUD/weapons/flaresmol.png",

}