return {
    {
        zone = "coniferousMountainside",
        subtitle = "-- Another Journey? --",
        displayName = "Coniferous Highlands",
        distanceTitle = "-- WOW!! --",
        distance = 10000,
        difficultyFunction = coniferousMountainsideDifficulty,
        transition = 500,
        current = 100,
        snowAmount = 3,
        currentIcons = 2,
        windSpeed = 300,
        musicManager = coniferousMountainsideMusicManager,
    },
    {
        zone = "devZone2",
        displayName = "Ice Plains",
        distanceTitle = "Starting Point",
        subtitle = "River's Source",
        distance = 24700,
        difficultyFunction = 0.01,
        transition = 300,
        current = iceplainsCurrent,
        currentIcons = 2,
        snowAmount = 5,
        windSpeed = 200,
        musicManager = icePlainsMusicManager,
    },
    {
        zone = "devZone",
        displayName = "Boulder Valley",
        distanceTitle = "-- 1.5KM --",
        subtitle = "Rock-Chain Gully",
        distance = 15000,
        difficultyFunction = boulderValleyDifficulty,
        transition = 0,
        snowAmount = boulderValleySnow,
        windSpeed = boulderValleyWind,
        current = boulderValleyCurrent,
        currentIcons = 3,
        chainLengthCoefficient = boulderValleyChainLengthCoefficient,
        musicManager = boulderValleyMusicManager,
    },
    {
        zone = "devZone2", --yes i know there is a file for the storm version. not using it yet
        displayName = "Storm Valley",
        subtitle = "Blizzard Approaching",
        distanceTitle = "-- 5KM --",
        distance = 49500,
        stormIntensity = boulderValleyStormIntensity_STORM,
        difficultyFunction = boulderValleyDifficulty_STORM,
        transition = 500,
        snowAmount = boulderValleySnow_STORM,
        windSpeed = boulderValleyWind_STORM,
        current = boulderValleyCurrent_STORM,
        currentIcons = 4,
        chainLengthCoefficient = boulderValleyChainLengthCoefficient_STORM,
        musicManager = stormValleyMusicManager,
    },
}