return {
    {
        zone = "coniferousHills",
        displayName = "Wooded Hills",
        subtitle = "Pine-Forested Foothills",
        distance = 2000,
        transition = 0,
        currentIcons = 2,
    },
    {
        zone = "coniferousHills-autumnGrove",
        displayName = "Wooded Hills",
        subtitle = "Pine-Forested Foothills",
        distance = 1000,
        transition = 0,
        currentIcons = 2,
    },
    {
        zone = "gruelingGrove",
        displayName = "Grueling Grove",
        subtitle = "Woodland of Eternal Suffering",
        distance = 14500,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "ruinsOfRegret",
        displayName = "Ruins of Regret",
        subtitle = "Ancient Site of Geared Cruelty",
        distance = 15000,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "clockworkCore",
        displayName = "Clockwork Catastrophe",
        subtitle = "Cog-filled Calamity",
        distance = 12000,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "autumnRapids-gravellyPlains",
        displayName = "_Clockwork Catastrophe",
        subtitle = "Cog-filled Calamity",
        distance = 1000,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "gravellyPlains",
        displayName = "Gravelly Plains",
        subtitle = "-- Almost There! --",
        distance = 3000,
        transition = 0,
        currentIcons = 3,
    },
}