return {
    {
        zone = "coniferousHills",
        displayName = "Wooded Hills",
        subtitle = "Pine-Forested Foothills",
        distance = 4500,
        transition = 0,
        currentIcons = 2,
    },
    {
        zone = "coniferousHills-autumnGrove",
        displayName = "Wooded Hills",
        subtitle = "Pine-Forested Foothills",
        distance = 1000,
        transition = 0,
        currentIcons = 2,
    },
    {
        zone = "autumnGrove",
        displayName = "Autumn Grove",
        subtitle = "Woodland of eternal Fall",
        distance = 19500,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "clockworkRuins",
        displayName = "Clockwork Ruins",
        subtitle = "Ancient site of geared locomotion",
        distance = 15000,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "clockworkCore",
        displayName = "Clockwork's Core",
        subtitle = "Origin of the cog",
        distance = 15000,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "autumnRapids",
        displayName = "Autumn Rapids",
        subtitle = "Fast-flowing stream",
        distance = 10000,
        transition = 0,
        currentIcons = 3,
    },

}