return {
    {
        zone = "icePlains",
        displayName = "Ice Plains",
        distanceTitle = "Starting Point",
        subtitle = "River's Source",
        distance = 23000,
        transition = 0,
        currentIcons = 2,
    },
    {
        zone = "icePlains-boulderValley",
        displayName = "Ice Plains",
        distanceTitle = "",
        subtitle = "",
        distance = 2000,
        transition = 0,
        currentIcons = 2,
    },
    {
        zone = "boulderValley",
        displayName = "Boulder Valley",
        distanceTitle = "-- 1.5KM --",
        subtitle = "Rock-Chain Gully",
        distance = 15000,
        transition = 0,
        currentIcons = 3,
    },
    {
        zone = "boulderValley", --yes i know there is a file for the storm version. not using it yet
        displayName = "Storm Valley",
        subtitle = "Blizzard Approaching",
        distanceTitle = "-- 5KM --",
        distance = 49000,
        transition = 0,
        currentIcons = 4,
    },
        {
        zone = "boulderValley-coniferousMountainside", --yes i know there is a file for the storm version. not using it yet
        displayName = "Storm Valley",
        subtitle = "",
        distanceTitle = "",
        distance = 2000,
        transition = 0,
        currentIcons = 4,
    },
    {
        zone = "coniferousMountainside",
        subtitle = "-- Almost There! --",
        displayName = "Coniferous Highlands",
        distanceTitle = "-- Almost There! --",
        distance = 9000,
        transition = 0,
        currentIcons = 2,
    },
}